project:
  type: website
  output-dir: docs

website:
  title: "Ally Detre"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv/cv.qmd
        text: CV
      - href: fieldphotos.qmd
        text: Field Photos
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

